"""CaseKBService: false-positive and history case retrieval + archival (ISSUE-043)."""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.db import models as orm
from app.models.case import (
    HistoryCase,
    history_case_metadata,
    history_case_to_text,
    make_chunk_id,
)
from app.models.enums import (
    DispositionIntentKind,
    DispositionPolicy,
    EventStatus,
    EventType,
    FinalVerdict,
    Severity,
    WritebackStatus,
)
from app.models.knowledge import KnowledgeChunk, RetrievedChunk
from app.models.workflow import derive_case_label
from app.services.knowledge_store import KnowledgeStore

FP_KB_NAME = "fp_case_kb"
HISTORY_KB_NAME = "history_case_kb"

# Mock-stage keyword expansions for fp_case_kb (attack_kb semantic path: issue #522).
_FP_KEYWORD_ALIASES: dict[str, str] = {
    "ops-change-bot": "ops-change-bot PC-OPS-JUMP-01 bulk login change window jump host",
}


class CaseKBService:
    """Search false-positive and historical cases; archive closed events as cases.

    Depends on :class:`KnowledgeStore` for vector/keyword retrieval and
    :class:`async_sessionmaker` for DB reads during archival.
    """

    def __init__(
        self,
        knowledge_store: KnowledgeStore,
        session_factory: async_sessionmaker[AsyncSession],
    ) -> None:
        self._kb = knowledge_store
        self._session_factory = session_factory

    # ------------------------------------------------------------------
    # Search
    # ------------------------------------------------------------------

    async def search_fp_cases(self, alert_text: str, top_k: int = 5) -> list[RetrievedChunk]:
        """Hybrid-search ``fp_case_kb`` for false-positive patterns matching *alert_text*."""
        keyword_query = _fp_keyword_query(alert_text)
        results = await self._kb.hybrid_search(
            FP_KB_NAME,
            alert_text,
            keyword_query=keyword_query,
            top_k=top_k,
        )
        # Mock embeddings produce non-semantic vector scores; prefer keyword/hybrid hits.
        if keyword_query != alert_text.strip():
            results = _prefer_keyword_hybrid_ranking(results)
        return results[:top_k]

    async def search_history_cases(
        self,
        query_text: str,
        event_type: str | None = None,
        top_k: int = 5,
    ) -> list[RetrievedChunk]:
        """Hybrid-search ``history_case_kb``, optionally filtered by *event_type* in metadata."""
        fetch_k = top_k if event_type is None else top_k * 3
        results = await self._kb.hybrid_search(HISTORY_KB_NAME, query_text, top_k=fetch_k)
        if event_type is not None:
            results = [r for r in results if r.metadata.get("event_type") == event_type]
            results = results[:top_k]
        return results

    # ------------------------------------------------------------------
    # Archival
    # ------------------------------------------------------------------

    async def archive_event_as_case(self, event_id: str) -> str:
        """Assemble a ``HistoryCase`` from a closed event and upsert into ``history_case_kb``.

        Returns the new *case_id*.
        """
        case_id = _derive_case_id(event_id)

        async with self._session_factory() as session:
            row = await session.get(orm.SecurityEvent, event_id)
            if row is None:
                raise ValueError(f"security_event not found: {event_id}")

            report = await session.scalar(select(orm.Report).where(orm.Report.event_id == event_id))
            if not _is_history_case_eligible(row, report):
                raise ValueError(f"event is not eligible for history_case_kb: {event_id}")

            event_type = EventType(row.event_type)
            verdict = FinalVerdict(row.final_verdict)
            case_label = derive_case_label(verdict)

            summary = report.summary if report and report.summary else row.title
            resolution = (
                f"Report generated by {report.generated_by or 'system'}; "
                f"verdict={verdict.value}; risk_score={row.risk_score}"
                if report
                else f"Closed with verdict={verdict.value}; risk_score={row.risk_score}"
            )

            entities_raw = row.entities or {}
            entity_parts: list[str] = []
            for field in ("accounts", "hosts", "ips", "domains", "processes", "files"):
                values = entities_raw.get(field, [])
                if values:
                    rendered = ",".join(_format_entity_item(v) for v in values)
                    entity_parts.append(f"{field}={rendered}")
            key_entities = "; ".join(entity_parts) if entity_parts else "none"
            response_outcomes = await _load_response_outcomes(session, row)
            successful_response = bool(response_outcomes) and all(
                bool(item["successful_response"]) for item in response_outcomes
            )

            history_case = HistoryCase(
                case_id=case_id,
                event_id=event_id,
                event_type=event_type,
                case_label=case_label,
                summary=summary,
                key_entities=key_entities,
                final_verdict=verdict.value,
                risk_score=int(row.risk_score or 0),
                resolution=resolution,
                closed_at=row.closed_at or datetime.now(UTC),
                successful_response=successful_response,
                response_outcomes=response_outcomes,
            )

        content = history_case_to_text(history_case)
        chunk_id = make_chunk_id(HISTORY_KB_NAME, case_id)
        meta = history_case_metadata(history_case)

        chunk = KnowledgeChunk(
            chunk_id=chunk_id,
            kb_name=HISTORY_KB_NAME,
            content=content,
            metadata=meta,
        )
        await self._kb.upsert_chunks(HISTORY_KB_NAME, [chunk])
        return case_id


def _is_history_case_eligible(event: orm.SecurityEvent, report: orm.Report | None) -> bool:
    """Apply the closed-case admission policy before knowledge persistence."""
    if event.status != EventStatus.CLOSED.value or report is None or event.external_unsynced:
        return False
    if event.final_verdict != FinalVerdict.NONE.value:
        return True
    return event.disposition_policy == DispositionPolicy.NOT_REQUIRED.value and (
        event.severity == Severity.LOW.value or int(event.risk_score or 0) <= 30
    )


async def _load_response_outcomes(
    session: AsyncSession,
    event: orm.SecurityEvent,
) -> list[dict[str, object]]:
    actions = list(
        await session.scalars(
            select(orm.Action)
            .where(
                orm.Action.event_id == event.event_id,
                orm.Action.action_category == "response",
                orm.Action.superseded_by_revision.is_(None),
            )
            .order_by(orm.Action.created_at.asc(), orm.Action.action_id.asc())
        )
    )
    active_outbox = list(
        await session.scalars(
            select(orm.DispositionOutbox)
            .where(
                orm.DispositionOutbox.event_id == event.event_id,
                orm.DispositionOutbox.superseded_by_disposition_id.is_(None),
            )
            .order_by(
                orm.DispositionOutbox.updated_at.desc(),
                orm.DispositionOutbox.outbox_id.asc(),
            )
        )
    )
    outbox_status_by_action: dict[str, str | None] = {}
    for row in active_outbox:
        outbox_status_by_action.setdefault(row.action_id, row.latest_writeback_status)
    terminal_confirmed = any(
        row.intent_kind == DispositionIntentKind.EVENT_STATUS_UPDATE.value
        and row.latest_writeback_status == WritebackStatus.CONFIRMED.value
        for row in active_outbox
    )
    policy = DispositionPolicy(event.disposition_policy)
    outcomes: list[dict[str, object]] = []
    for action in actions:
        effect_status = action.effect_verification_status
        writeback_status = outbox_status_by_action.get(action.action_id) or action.writeback_status
        successful = _response_succeeded(
            effect_status=effect_status,
            writeback_status=writeback_status,
            policy=policy,
            terminal_confirmed=terminal_confirmed,
        )
        outcomes.append(
            {
                "action_id": action.action_id,
                "tool_name": action.tool_name,
                "effect_status": effect_status,
                "writeback_status": writeback_status,
                "successful_response": successful,
            }
        )
    return outcomes


def _response_succeeded(
    *,
    effect_status: str | None,
    writeback_status: str | None,
    policy: DispositionPolicy,
    terminal_confirmed: bool,
) -> bool:
    effect_verified = effect_status == "verified"
    writeback_confirmed = writeback_status == WritebackStatus.CONFIRMED.value
    synchronization_ok = (
        policy is DispositionPolicy.NOT_REQUIRED or writeback_confirmed or terminal_confirmed
    )
    return effect_verified and synchronization_ok


def _fp_keyword_query(alert_text: str) -> str:
    """Expand distinctive FP markers for keyword search under mock embeddings."""
    lowered = alert_text.lower()
    for needle, expansion in _FP_KEYWORD_ALIASES.items():
        if needle in lowered:
            return expansion
    return alert_text.strip()


def _prefer_keyword_hybrid_ranking(results: list[RetrievedChunk]) -> list[RetrievedChunk]:
    """Rank keyword/hybrid hits above mock-vector noise when aliases were applied."""
    return sorted(
        results,
        key=lambda row: (
            0 if row.retrieval_method in {"keyword", "hybrid"} else 1,
            -row.score,
            row.chunk_id,
        ),
    )


def _format_entity_item(value: object) -> str:
    """Render an entity list item as a stable, human-readable token."""
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for key in (
            "username",
            "hostname",
            "entity_id",
            "name",
            "ip",
            "domain",
            "path",
            "process_name",
        ):
            item = value.get(key)
            if item:
                return str(item)
    return str(value)


def _derive_case_id(event_id: str) -> str:
    """Deterministically derive a ``case-{8 hex}`` ID from an event_id."""
    digest = hashlib.sha256(event_id.encode()).hexdigest()
    return f"case-{digest[:8]}"
